### PR TITLE
Attempt at HTTLACS 7 approx Pi

### PR DESCRIPTION
**Pull request by primitivecube**
I didn't really understand this question. I interested in other people's approaches, and where I might have gone wrong

### CODE REVIEW

**Comment by primitivecube** [comment]
Hi, if anyone has something to comment, then please comment here. Particularly if you are student at Massey studying 159.171, but I'll take suggestions from anyone :)

**Comment by winterforge** [comment]
#1 
# Hi Brett. I am on the same course and came here after reading your post
# here is my attempt at this question. We are approximating pi by using the ratio of circle area to board area. The maths is sound but imo they ruin it by relying on random chance.
# The higher the number of "throws" the greater the accuracy of the approximation.
# I am not all that good at explaining stuff, so I hope you can follow what I have done

import turtle
import math
import random

fred = turtle.Turtle()

wn = turtle.Screen()
wn.setworldcoordinates(-1,-1,1,1)

fred.up()

numdarts = 100  # increase this for a better approximation
insideCount=0  # initialises the counter for counting darts that land in the circle

for i in range(numdarts):
    randx = 2*(random.random())-1  # gives a random number between -1 and 1
    randy = 2*(random.random())-1
    fred.goto(randx,randy)
    if fred.distance(0,0)<=1:
        fred.color("red")
        insideCount+=1  # increments counter if fred inside circle
    else:
        fred.color("blue")
    fred.dot()
    
piApproximation=(insideCount/numdarts)*4  # gives the approximation
print(piApproximation)
    


wn.exitonclick()

**Comment by winterforge** [comment]
seems when I copied that in the indentations of the for and if loops was removed. you will need to add them back. oops.

**Comment by primitivecube** [comment]
Thanks for sharing your code winterforge,  I'm not sure how to properly collaborate on code yet either, but we'll get there. Your code demonstrated the one difference why your version worked and mine didn't; it was due to (insideCount/numdarts)*4 being the correct multiplication (I had (insideCount/numdarts)*3.14. That got me thinking that the '4' must be important about the relationship between a circle and an inscribing square, so I investigated that and now I really understand how the program works. I've added comments to the program to explain the circle/square relationship in detail, thank you. I'll close this pull request now and update the master branch file.

**Pull request merged**
